### PR TITLE
Allow to read pulse length and set it.

### PR DESCRIPTION
**Pull request by scsirdx**
Hello!

I found, that different 433 devices (power outlets, etc..) use different pulse length. So i modified code to support this.
rpi-433 default pulse length was 353.

### CODE REVIEW

**Comment by eroak** [comment]
As i told you in your previous pull request, i'm currently working on a new version of rpi-433. I'm gonna see how i can merge your good ideas.

Can you please give me links and sources for that different pulse length ? Thank you in advance !!

**Comment by techniq** [comment]
@eroak any progress on the new version?  I too need to be able to set the pulse length

**Comment by scsirdx** [comment]
@eroak Sorry for the late answer. Missed notification in my inbox.
There are many discussions about pulse length. For example: http://www.wes.id.au/2013/07/decoding-and-sending-433mhz-rf-codes-with-arduino-and-rc-switch/
or
https://discuss.ninjablocks.com/t/433-pulse-length/800

@techniq you can temporary use my fork: https://github.com/scsirdx/rpi-433

**Comment by techniq** [comment]
Thanks @scsirdx.  I'll take a look at your fork.  I've also been looking at the following libraries, which have support for setting the pulse length as well, although they don't appear to support retrieving the codes, just transmitting.
- https://github.com/n8henrie/node-rcswitch-gpiomem
- https://github.com/tjanson/PiSwitch

**Comment by eroak** [comment]
You can now set/get the pulse length with the new version of rpi-433. Thank you very much for your suggestions !!

**Pull request closed without merging**
